// Generated by CoffeeScript 1.8.0
module.exports = function(grunt) {
  grunt.loadNpmTasks('grunt-contrib-coffee');
  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-mocha-test');
  return grunt.initConfig({
    watch: {
      coffee: {
        files: 'lib/*.coffee',
        tasks: ['coffee:compile', 'mochaTest:test']
      },
      test: {
        files: 'spec/**/*.js',
        tasks: ['mochaTest:test']
      }
    },
    coffee: {
      compile: {
        expand: true,
        flatten: true,
        cwd: "" + __dirname + "/lib/",
        src: ['*.coffee'],
        dest: 'public/javascript/',
        ext: '.js'
      }
    },
    mochaTest: {
      test: {
        options: {
          reporter: 'spec',
          quiet: false
        },
        src: ['spec/**/*.js']
      }
    }
  }, grunt.registerTask('default', ['coffee', 'mochaTest']));
};
